{ username, hostname, ... }:
{
  imports = [
    ./hardware-configuration.nix
    ../../modules/core/boot.nix
    ../../modules/core/nix.nix
    ../../modules/core/user.nix
    ../../modules/core/locale.nix
    ../../modules/core/networking.nix
    ../../modules/core/audio.nix
    ../../modules/core/security.nix
    ../../modules/core/filesystems.nix
    ../../modules/hardware/nvidia-amd.nix
    ../../modules/sessions/hyprland.nix
    ../../modules/programs/apps.nix
    ../../modules/gaming/gaming.nix
  ];

  networking.hostName = hostname;

  # Keep this at the value generated by your installer for a new install.
  # If the graphical installer generated 25.05/25.11, use that value.
  system.stateVersion = "25.11";
}
